# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5961064b5fa9d6a0bbc3df7b679cb1ca"
name = "Filter3april"
handle = "filter3april"
application_url = "https://separated-audi-tripadvisor-examines.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-779a2240.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_listings,read_products,write_products"

[auth]
redirect_urls = [
  "https://separated-audi-tripadvisor-examines.trycloudflare.com/auth/callback",
  "https://separated-audi-tripadvisor-examines.trycloudflare.com/auth/shopify/callback",
  "https://separated-audi-tripadvisor-examines.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
