# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cda589aa1d4db0408131cad372bcde7d"
name = "exampleone"
handle = "exampleone-2"
application_url = "https://gossip-var-sara-shares.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "phanomgetcustomer.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_listings,read_products,write_products"

[auth]
redirect_urls = [
  "https://gossip-var-sara-shares.trycloudflare.com/auth/callback",
  "https://gossip-var-sara-shares.trycloudflare.com/auth/shopify/callback",
  "https://gossip-var-sara-shares.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[app_proxy]
url = "https://gossip-var-sara-shares.trycloudflare.com"
subpath = "proxies"
prefix = "apps"

[pos]
embedded = false
